// <auto-generated />
namespace Turnos_Sala_de_Ensayo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class marian : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(marian));
        
        string IMigrationMetadata.Id
        {
            get { return "202007020028016_marian"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
